repo_name: aaraar
repo_url: https://github.com/christiandeange/aaraar
site_name: aaraar
site_url: https://christiandeange.github.io/aaraar/
site_author: Christian De Angelis
site_description: 'A Gradle Plugin for creating a merged aar file'
copyright: 'Copyright 2023 Christian De Angelis'
remote_branch: gh-pages

theme:
  name: 'material'
  logo: assets/logo.png
  custom_dir: docs/overrides
  icon:
    repo: fontawesome/brands/github
  features:
    - content.code.copy
    - content.tabs.link
    - navigation.instant
    - toc.integrate
  palette:
    - scheme: default
      media: "(prefers-color-scheme: light)"
      primary: blue grey
      toggle:
        icon: material/brightness-5
        name: Switch to dark mode

    - scheme: slate
      media: "(prefers-color-scheme: dark)"
      primary: blue grey
      toggle:
        icon: material/brightness-3
        name: Switch to light mode

markdown_extensions:
  - toc:
      permalink: true
  - pymdownx.caret
  - pymdownx.details
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - admonition

plugins:
  - search

nav:
  - 'Overview': index.md
  - 'API Reference': kdoc/index.html
