[versions]
agp-latest = "9.2.1"
agp-tools = "32.2.1"
detekt = "1.23.8"
dokka = "2.2.0"
kotlin = "2.3.21"
maven-publish = "0.36.0"

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }

[libraries]
kotlin-bom = { module = "org.jetbrains.kotlin:kotlin-bom", version.ref = "kotlin" }

agp-api7 = { module = "com.android.tools.build:gradle-api", version = "7.4.2" }
agp-api8 = { module = "com.android.tools.build:gradle-api", version = "8.13.2" }
agp-api9 = { module = "com.android.tools.build:gradle-api", version = "9.2.1" }
agp-api-latest = { module = "com.android.tools.build:gradle-api", version.ref = "agp-latest" }
agp-layoutlib = { module = "com.android.tools.layoutlib:layoutlib-api", version.ref = "agp-tools" }
agp-tools-common = { module = "com.android.tools:common", version.ref = "agp-tools" }
agp-tools-manifestmerger = { module = "com.android.tools.build:manifest-merger", version.ref = "agp-tools" }
agp-tools-sdk = { module = "com.android.tools:sdk-common", version.ref = "agp-tools" }

asm = { module = "org.ow2.asm:asm-commons", version = "9.10.1" }
javassist = { module = "org.javassist:javassist", version = "3.31.0-GA" }
decompiler = { module = "com.jetbrains.intellij.java:java-decompiler-engine", version = "233.14475.28" }
kotlin-metadata = { module = "org.jetbrains.kotlin:kotlin-metadata-jvm" }

jimfs = { module = "com.google.jimfs:jimfs", version = "1.3.1" }

gson = { module = "com.google.code.gson:gson", version = "2.14.0" }
kotlinxml = { module = "org.redundent:kotlin-xml-builder", version = "1.9.3" }

dokka-plugin = { module = "org.jetbrains.dokka:dokka-gradle-plugin", version.ref = "dokka" }
maven-publish = { module = "com.vanniktech:gradle-maven-publish-plugin", version.ref = "maven-publish" }

detekt-plugin = { module = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin", version.ref = "detekt" }
detekt-rules-formatting = { module = "io.gitlab.arturbosch.detekt:detekt-formatting", version.ref = "detekt" }

kotest = { module = "io.kotest:kotest-assertions-core", version = "6.2.1" }
