complexity:
  LongParameterList:
    allowedFunctionParameters: 999
    allowedConstructorParameters: 999
  LongMethod:
    allowedLines: 100
  CyclomaticComplexMethod:
    allowedComplexity: 20
  TooManyFunctions:
    allowedFunctionsPerClass: 20

naming:
  ConstructorParameterNaming:
    parameterPattern: "[a-z_][A-Za-z0-9]*"
    privateParameterPattern: "[a-z_][A-Za-z0-9]*"

ktlint:
  ClassSignature:
    # https://github.com/detekt/detekt/issues/9083
    active: false
  Filename:
    active: false
  FunctionExpressionBody:
    active: false
  FunctionSignature:
    forceMultilineWhenParameterCountGreaterOrEqualThan: 2
    indentSize: 2
  Indentation:
    indentSize: 2
