complexity:
  LongParameterList:
    functionThreshold: 999
    constructorThreshold: 999
  LongMethod:
    threshold: 100
  CyclomaticComplexMethod:
    threshold: 25
  TooManyFunctions:
    thresholdInClasses: 20

naming:
  ConstructorParameterNaming:
    parameterPattern: "[a-z_][A-Za-z0-9]*"
    privateParameterPattern: "[a-z_][A-Za-z0-9]*"

formatting:
  Filename:
    active: false
  Indentation:
    indentSize: 2

style:
  MagicNumber:
    active: false
