complexity:
  LongParameterList:
    functionThreshold: 999
    constructorThreshold: 999
  LongMethod:
    threshold: 100
  CyclomaticComplexMethod:
    active: false
  TooManyFunctions:
    thresholdInClasses: 20

naming:
  ConstructorParameterNaming:
    parameterPattern: "[a-z_][A-Za-z0-9_]*"
    privateParameterPattern: "[a-z_][A-Za-z0-9_]*"
  VariableNaming:
    variablePattern: "[a-z_][A-Za-z0-9_]*"
    privateVariablePattern: "[a-z_][A-Za-z0-9_]*"

formatting:
  Filename:
    active: false
  Indentation:
    indentSize: 2

style:
  MagicNumber:
    active: false
