name: Deploy Docs

on:
  workflow_call:
  workflow_dispatch:

permissions:
  contents: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  deploy-mkdocs:
    runs-on: ubuntu-latest
    if: github.repository == 'christiandeange/aaraar'

    steps:
      - uses: actions/checkout@v4
      - uses: gradle/actions/wrapper-validation@v3
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
          check-latest: true
      - uses: actions/setup-python@v5
        with:
          python-version: 3.x

      - run: echo "cache_id=$(date --utc '+%V')" >> $GITHUB_ENV
      - uses: actions/cache@v4
        with:
          key: mkdocs-material-${{ env.cache_id }}
          path: .cache
          restore-keys: |
            mkdocs-material-

      - name: Build API Reference
        run: ./gradlew dokkaHtmlCollector

      - name: Install MkDocs
        run: pip install mkdocs-material

      - name: Build MkDocs
        run: |
          rm docs/changelog.md
          cp CHANGELOG.md docs/changelog.md
          mkdocs build

      - name: Deploy MkDocs to GitHub Pages
        run: mkdocs gh-deploy --force
