name : Publish

on :
  push :
    tags :
      - 'v*.*.*'

jobs :
  publish-release :
    runs-on : ubuntu-latest
    if : github.repository == 'christiandeange/aaraar'
    timeout-minutes : 10

    steps :
      - uses : actions/checkout@v3
      - uses : gradle/wrapper-validation-action@v1
      - uses : actions/setup-java@v3
        with :
          distribution : 'temurin'
          java-version : '17'
          check-latest : true

      - name : Publish Release
        env :
          SONATYPE_NEXUS_USERNAME : ${{ secrets.SONATYPE_NEXUS_USERNAME }}
          SONATYPE_NEXUS_PASSWORD : ${{ secrets.SONATYPE_NEXUS_PASSWORD }}
          ARTIFACT_SIGNING_PRIVATE_KEY : ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY }}
          ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD : ${{ secrets.ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD }}
        run : |
          ORG_GRADLE_PROJECT_mavenCentralUsername="$SONATYPE_NEXUS_USERNAME" \
          ORG_GRADLE_PROJECT_mavenCentralPassword="$SONATYPE_NEXUS_PASSWORD" \
          ORG_GRADLE_PROJECT_signingInMemoryKey="$ARTIFACT_SIGNING_PRIVATE_KEY" \
          ORG_GRADLE_PROJECT_signingInMemoryKeyPassword="$ARTIFACT_SIGNING_PRIVATE_KEY_PASSWORD" \
          ./gradlew clean publish --no-build-cache --no-daemon --stacktrace
